#!/usr/bin/env bash
# Configures a new ubuntu machine by installing

sudo apt-get update -y -qq &&
    sudo apt-get install nginx -y

sudo service nginx start
sudo ufw allow 'Nginx HTTP'

# Creating new index
echo -e "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Restarting nginx
sudo service nginx restart